export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT = "LOGOUT";

export const UPDATE_USER = "GET_USER";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";

export const UPDATE_ACCOUNT_INFO = "UPDATE_ACCOUNT_INFO";

export const FETCH_ALL_ACCOUNTS = "FETCH_ALL_ACCOUNTS";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const FETCH_ALL_DRUGS = "FETCH_ALL_DRUGS";

export const UPDATE_DRUG = "UPDATE_DRUG";

export const DELETE_DRUG = "DELETE_DRUG";
